[project]
name = "rag-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.1",
    "faiss-cpu>=1.13.2",
    "giskard[llm]>=2.5.0",
    "google-cloud-storage>=3.9.0",
    "griffe<1.0.0",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.15",
    "langchain-google-community[gcs]>=3.0.5",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.10",
    "pymupdf>=1.27.1",
    "pypdf>=6.7.3",
    "ragas>=0.4.3",
    "rapidfuzz>=3.14.3",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "sentence-transformers>=5.2.3",
    "tiktoken>=0.12.0",
]
